apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume
spec:
  storageClassName: manual
  hostPath:
    path: /home/ryan/k8s-mongodb-data
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  volumeMode: Filesystem