apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
spec:
  storageClassName: manual
  volumeName: mongodb-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi